{
 "title": "Docker monitoring (cadvisor-exporter)",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "container monitor" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Env",
    "label": "环境",
    "query": {
     "query": "label_values(container_last_seen{container_label_env=~\".*\"},container_label_env)"
    }
   },
   {
    "name": "Category",
    "label": "项目",
    "query": {
     "query": "label_values(container_last_seen{container_label_category=~\".*\" ,container_label_env=~\"$Env\"},container_label_category)"
    }
   },
   {
    "name": "Container",
    "label": "容器",
    "query": {
     "query": "label_values(container_last_seen{container_label_category=~\"$Category\",name!~\"container-exporter.*|zabbix.*|prometheus.*\"},name)"
    }
   },
   {
    "name": "responsible",
    "label": "负责人",
    "query": {
     "query": "label_values(container_last_seen{container_label_category=~\"$Category\", name=~\"$Container\"},container_label_responsible)"
    }
   },
   {
    "name": "Lang",
    "label": "项目语言",
    "query": {
     "query": "label_values(container_last_seen{name=~\"$Container\",name=~\"$Container\", container_label_responsible=~\"$responsible\"},container_label_lang)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "环境 $Env 容器CPU使用率",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Env",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU使用率(业务：$Category - 容器：$Container - 语言：$Lang - 负责人：$responsible)",
   "type": "timeseries",
   "description": "$Category ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "repeat": "Container",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{name!~\".*exporter.*|zabbix.*|prometheus.*\", container_label_category=~\"$Category\", name=~\"$Container\",container_label_env=\"$Env\"}[1m])) without (cpu)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "环境 $Env 容器内存使用",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Env",
   "targets": [
    {}
   ]
  },
  {
   "title": "内存状态(业务：$Category - 容器：$Container - 语言：$Lang - 负责人：$responsible)",
   "type": "graph",
   "description": "$Category ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "Container",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"container-exporter.*|zabbix.*|prometheus.*\",name=~\"$Container\",container_label_env=\"$Env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "All Container ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前 【$Env】所有节点中的容器CPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*deploy.*|.*exporter.*\",image!=\"\", job=\"cnosul-prometheus\",container_label_env=\"$Env\" }[5m])) by (name, instance,group) *100",
     "legendFormat": "容器：{{name}} 节点： {{instance}}"
    }
   ]
  },
  {
   "title": "当前 【$Env】所有节点中的容器内存使用量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{image!=\"\", name!~\".*deploy.*\",job=\"cnosul-prometheus\",container_label_env=\"$Env\"}) by (name,instance)",
     "legendFormat": "容器：{{name}} 节点：{{instance}}"
    }
   ]
  },
  { "title": "采集器状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "容器数据采集器CPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*cadvisor-exporter.*\", image!=\"\", job=\"cnosul-prometheus\"}[5m])) by (name, instance,group) *100",
     "legendFormat": "运行在 {{instance}}  上面的   {{name}} 内存使用量"
    }
   ]
  },
  {
   "title": "宿主机数据采集器内存消耗",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=~\".*node-exporter.*\", image!=\"\", job=\"cnosul-prometheus\"}",
     "legendFormat": "运行在 {{instance}}  上面的   {{name}} 内存使用量"
    }
   ]
  }
 ]
}